- hosts: all
  tasks:
    - name: docker repo
      yum_repository:
        name: docker
        description: Adding Dockerrepo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

    - command: yum install docker-ce --nobest
